### ISSUE TITLE
Error of sending of the e-mail of confirmation

### ISSUE THREAD

**Issue by IManAsap** [bestmomo/laravel-email-confirmation#11]
After several attempts of installation of you package, I have systematically the following error having clicked on the button "Register" of the page/register. The user is created well in the table users. Further to some investigations, it seems that the problem occurs at the level of the sending of the e-mail of confirmation via the system of notification.

Thank you in advance for your help.

(in addition [laravel.log](https://github.com/bestmomo/laravel-email-confirmation/files/1637757/laravel.log))

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_PARSE)
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

All frames :
1 Symfony\Component\Debug\Exception\FatalThrowableError
…\vendor\symfony\css-selector\XPath\Extension\AttributeMatchingExtension.php : 46
0 {main}…\public\index.php : 0

**My environment:**
- wamp 3.1.1
- php CLI 7.2.2
- php Web 7.0.23
- mysql 5.7.19

**Here is the procedure of installation that I followed:**
- composer create-project --prefer-dist laravel/laravel MineInFrance
- php artisan make:auth
- composer require bestmomo/laravel-email-confirmation
- php artisan migrate
- In LoginController replacement of use Illuminate\Foundation\Auth\AuthenticatesUsers; by use Bestmomo\LaravelEmailConfirmation\Traits\AuthenticatesUsers;
- InRegisterController : replacement of use Illuminate\Foundation\Auth\RegistersUsers; by use Bestmomo\LaravelEmailConfirmation\Traits\RegistersUsers;
- In ResetPasswordController replacement of use Illuminate\Foundation\Auth\ResetsPasswords; by use Bestmomo\LaravelEmailConfirmation\Traits\ResetsPasswords;

**Comment by bestmomo** [comment]
Hi,

Looks like there is a syntax error somewhere, but I can reproduce your issue with the same actions...

How are your views ? Laravel installation ones ?

**Comment by IManAsap** [comment]
Hi 

First of all, thank you for your fast return.

My installation is a basic installation in which I modified nothing set apart what is indicated in the procedure of installation of your packages:
Stage 1: composer create-project - prefer-dist laravel / laravel MineInFrance
Stage 2: php artisan make:auth 
Stage 3: composer require bestmomo / laravel-email-confirmation
Stage 4: php artisan migrate
Stage 5: modification indicated in the section "Installation" of the page https://github.com/bestmomo/laravel-email-confirmation
Stage 6: I throw the Web application which exists by default in Laravel, I click on the named hypertext link which is situated above on the right of the homepage, i enter a name an e-mail address and a password, and finally I click on blue button name 'Register', the error appears at this moment.

To help you, here is the zip of my project : [monProjet.zip](https://github.com/bestmomo/laravel-email-confirmation/files/1640095/monProjet.zip)



Thank you in advance for your help.

**Comment by bestmomo** [comment]
Sorry but with your project I dont get this error...

**Comment by IManAsap** [comment]
Here is a screenshot of the error [scs.pdf](https://github.com/bestmomo/laravel-email-confirmation/files/1640621/scs.pdf)

**Comment by IManAsap** [comment]
I have just seen your answer, it confirms that the problem come from my application environment.
My problem and that I ignore what causes this error, indeed I begin with Laravel, It's thus difficult for me to know or to look for the cause....

**Comment by bestmomo** [comment]
Do you use Windows ?

**Comment by IManAsap** [comment]
Yes Windows 10 Pro v1709

**Comment by bestmomo** [comment]
Use [Laragon](https://laragon.org/) to have a cool local development environment.

**Comment by IManAsap** [comment]
Hi,
OK, I am going to be interested on this matter. Has t he a configuration of preference there?

**Comment by bestmomo** [comment]
Just take and install **Laragon Wamp** version.

**Comment by IManAsap** [comment]
Good evening, 
I found the reason of this error. Indeed this has nothing to do with your module, but with the system of translation of symfony of Laravel 5.5 who requires PHP 7.1
