### ISSUE TITLE
Adding a new lang file in Arabic

### ISSUE THREAD

**Issue by kmuharam** [bestmomo/laravel-email-confirmation#2]
Hello and thanks for this package :)

Using L5.4, my app locale is set to `ar` and `app()->getLocale()` returns `'ar'`. 
I created a new directory in `resources/lang/vendor/confirmation/ar` and translated `confirmation.php` to Arabic but I always get the English version.

**Comment by bestmomo** [comment]
Hello,

Looks weird...

Does it work if you set "fr" locale ?

**Comment by kmuharam** [comment]
Just tried `app()->setLocale('fr')`, still getting English version.

**Comment by bestmomo** [comment]
Where do you set `app()->setLocale('...')` ?

**Comment by kmuharam** [comment]
I'm using a pckage to handle multilanguage versions of my app, locale is set in a middleware https://github.com/keevitaja/linguist
I did a `dd(app()->getLocale())` in `LoginController::login` and returned `'ar'`.

**Comment by bestmomo** [comment]
Try make your **dd** in constructor of **RegisterController**.

**Comment by kmuharam** [comment]
Sorry for the delay @bestmomo ,

In `RegisterController` if the url is `localhost:8000/en/signin` returns `'en'`, and `localhost:8000/ar/signin` returns `'ar'`.

**Comment by kmuharam** [comment]
Hmmm, sorry about that, it was my error. Solved now.

**Comment by kmuharam** [comment]
BTW, I've been contributing to Fedora Linux translation project for 2 years now, I'm a member of the Arabic lang team. If you want to add Arabic to your package, here is my translation:

```
return [
    'email-title' => 'تأكيد البريد الإلكتروني',
    'email-intro'=> 'لتأكيد بريدك الإلكتروني، رجاءً قم بالصغط على الرابط ادناه',
    'email-button' => 'تأكيد البريد الإلكتروني',
    'message' => 'شكراً للتسجيل، رجاءً قم بمراجعة بريدك الإلكتروني للتأكيد.',
    'success' => 'لقد تم تأكيد بريدك الإلكتروني بنجاح! يمكنك الآن تسجيل الدخول.',
    'again' => 'رجاءً قم بتأكيد بريدك الإلكتروني حتى تتمكن من تسجيل الدخول.' .
                '<br>إذا لم تصلك رسالة التأكيد، قم بفتح ملف الرسائل الغير مرغوب بها (Spam).'.
                '<br>لإعادة إرسال رسالة التأكيد، <a href="' . url('confirmation/resend') . '" class="alert-link">إضغط هنا</a>.',
    'resend' => 'تم إرسال رسالة التأكيد بنجاح، قم بمراجعة بريدك الإلكتروني.'
];
```

**Comment by bestmomo** [comment]
Thanks for this translation added in new release.

**Comment by kmuharam** [comment]
No problem :)
