### ISSUE TITLE
how can I change the confirmation mail text or design ?

### ISSUE THREAD

**Issue by towfiq-ul** [bestmomo/laravel-email-confirmation#26]
how can I change the confirmation mail text or design ?

**Comment by bestmomo** [comment]
Hello

You can publish the notification:

**php artisan confirmation:notification**

**Comment by towfiq-ul** [comment]
It is working fine . but I want to change the html and css design along with message.

**Comment by bestmomo** [comment]
You can use the standard Laravel  publish:

**php artisan vendor:publish --tag=laravel-notifications**

You get the template in **resources/views/vendor/notifications directoryresources/views/vendor/notifications** directory.

**Comment by towfiq-ul** [comment]
Thank You <3
