### ISSUE TITLE
Sqlite DB driver

### ISSUE THREAD

**Issue by vladshoob** [bestmomo/laravel-email-confirmation#27]
Using phpunit tests throws

BadMethodCallException: SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification.

Solved by commenting out 2 dropcolumn method from migration and allowing users_table migration to clean a table fully.

**Comment by bestmomo** [comment]
Right,

Corrected with [this commit](https://github.com/bestmomo/laravel-email-confirmation/commit/ab5ba9c25fe37df8d45d3f71ef7fb09d919eca92).

**Comment by vladshoob** [comment]
@bestmomo thanks for your effort to keep library updated. I think it will solve the issue for most users.

I just checked it, and it seems like ok, but I received another error.

Error: Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found

And was able to fix this error by installing
composer require doctrine/dbal
following this github issue https://github.com/rappasoft/laravel-5-boilerplate/issues/785

**Comment by bestmomo** [comment]
I got the same error, Sqlite needs this package for column action.

**Comment by mansouryaacoubi** [comment]
@bestmomo Why did you drop the **confirmed**-column? I have been using it in my application. Should I create my own migration to add the **confirmed**-column?

Would just like to understand why this commit was necessary.
I 'm using MySQL.

Mansour

**Comment by bestmomo** [comment]
Hello

I dont drop the **confirmed-column**, just change syntax for **down** method to make it work for SQLite.

**Comment by vladshoob** [comment]
I think this is about some change from version 1.1.4 to 1.1.5.
My migrations were published not in /migrations directory, but somewhere else, hidden "magic" place.

And after update migration is no longer runnable. So seeds are failing. And then registration is not possible because there are no such columns in users table.

Publishing gives no success.

I assume, for this another issue can be opened.

**Comment by bestmomo** [comment]
With version 1.1.5 migration must be published with:
**php artisan vendor:publish --provider="Bestmomo\LaravelEmailConfirmationServiceProvider" --tag="confirmation:migrations"**
