### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by jasperf** [bestmomo/laravel-email-confirmation#29]
Would a Laravel 6 upgrade be tough for this package? Or is this package no longer needed perhaps due to Laravel changes since?

**Comment by bestmomo** [comment]
Laravel no longer needs this package since [Email Verification Core](https://laravel.com/docs/6.x/verification).

**Comment by jasperf** [comment]
Thanks @bestmomo . Thought so. Building a [Laravel 6 Kubernetes](https://github.com/Larastudio/laravel-k8) setup based on your Laravel 5.5 setup so was going through all the fixes. Will remove Email Verification as Laravel 6 already uses it.

**Comment by Mutahhar** [comment]
I am working on a project that someone else built. So to easily upgrade to `laravel 6` Can anyone please point out the steps to upgrade to `laravel 6` and use its Email Verification and removing of this package?
