### ISSUE TITLE
Get a new confirmation email - not work!

### ISSUE THREAD

**Issue by diominandrew** [bestmomo/laravel-email-confirmation#4]
After editing the file RegistersUsers.php all work!

public function resend(Request $request)
    {
        if ($request->session()->has('user_id')) {

            $model = config('auth.providers.users.model');

            $user = $model::findOrFail($request->session()->get('user_id'));

        // add
        $user->confirmation_code = str_random(30);
        $user->save();
        //

            $this->notifyUser($user);
            
            return redirect(route('login'))->with('confirmation-success', trans('confirmation::confirmation.resend'));
        }

        return redirect('/');
    }

**Comment by bestmomo** [comment]
Hello

The resend is only to get again the reset link and the user must already have the **confirmation_code** in **users** table, that is created on registration.

**Comment by diominandrew** [comment]
so on successful confirmation is deleted **confirmation_code** in users table

**Comment by bestmomo** [comment]
On successful confirmation why to ask for a resend ?

**Comment by diominandrew** [comment]
Excuse me. You're right. I had users before I installed your solution. Thank you for your work!
