### ISSUE TITLE
More control in login check

### ISSUE THREAD

**Issue by shiroamada** [bestmomo/laravel-email-confirmation#6]
Hi,

How do I add more control in login checking?
I got extra field want to check for membership_expired_at, if the date expired, they are not able to login.

How do I added extra flow after your login()?

**Comment by bestmomo** [comment]
Hi,

Override **AuthenticatesUsers** trait with your own. Get code in my package and add your extra check.

**Comment by shiroamada** [comment]
thanks!
Just for more detail how to override trait, can reference here. 
https://medium.com/@simonhamp/why-and-how-to-override-laravel-s-built-in-auth-controller-methods-60f070897ac6

**Comment by bestmomo** [comment]
If you use my package just copy **AuthenticatesUsers** trait from my package to your **Controllers\Auth** folder, change namespace for `namespace App\Http\Controllers\Auth` and add your code, declare your trait in **LoginController** instead of mine.

**Comment by shiroamada** [comment]
Thanks @bestmomo!
I actually have 2 login controller. (in two diff sub-domain)
one of it, I am using your package.
1. Login screen, after login, I redirect to /home.
2. Another one, I want it after login redirect to /dashboard
How do I set the redirectTo from another controller to  `protected $redirectTo = '/dashboard';`

I added to my Traits or Controller both also not working. Any place I missed

**Comment by bestmomo** [comment]
You can set each controller with a custom **$redirectTo**.

**Comment by shiroamada** [comment]
Ya, as I mention

> I added to my Traits or Controller both also not working. Any place I missed

I added protected $redirectTo = '/dashboard'; in my controller and traits, it still redirect to /home which is set under my default LoginController.

2.
I run a test in a new project with Laravel 5.5.27
only included your package.
And I change the LoginController AuthenticatesUsers Trait with you package. The $redirectTo does not work.

```
namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Bestmomo\LaravelEmailConfirmation\Traits\AuthenticatesUsers;

//use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/dashboard';
```

It just redirect back to /login page

**Comment by bestmomo** [comment]
There is something odd because I made a new test with Laravel 5.5.27 with my package and I get a good redirection with **$redirectTo** in **LoginController**. My trait doesn't change redirection logic but only override **login** method.

**Comment by shiroamada** [comment]
OK, my bad for the new installation. I didn't enable the error message. It redirect back it is because
```
You must verify your email before you can access the site. 
If you have not received the confirmation email check your spam folder.
To get a new confirmation email please click here.
```

For my another project. It works fine after I changed my TLD from .localhost to .test. Maybe something cache happen in between.

Thanks @bestmomo all solved.
