### ISSUE TITLE
No Confirmation code and Page Not Found(404) on resend email verification code

### ISSUE THREAD

**Issue by apal21** [bestmomo/laravel-email-confirmation#8]
I deployed my app on server, after 1 month I added email confirmation in my code. It is working fine for new registered users but for old users it is sending `http://localhost:8000/confirmation/1`.

There is no confirmation code in this URL so it cannot find in route thus gives Page Not Found.

**Comment by bestmomo** [comment]
The package adds the **confirmation_code** column with migration to **users** table. When someone registers the trait **RegistersUsers** save a 30 characters random string in this column. But as you added the package as users where already registered there is no value for them in this column.

Now do you want these users confirm ? If yes add a random value in this column. If not just set **true** to **confirmed** column.

**Comment by apal21** [comment]
Okay Thank you...
