### ISSUE TITLE
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

### ISSUE THREAD

**Issue by ghost** [bestmomo/laravel-email-confirmation#9]
I have followed your instructions and installed the package and configurations.

When i click on resend confirmation email on the login page alert message, i get the following error

`Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "`

How to solve this?

**Comment by bestmomo** [comment]
Check your mail configuration.

**Comment by ghost** [comment]
Yeah. This link below helped me.
[https://stackoverflow.com/questions/30556773/how-to-fix-stream-socket-enable-crypto-ssl-operation-failed-with-code-1](url)
